spring:
  datasource:
    initialize: true
    schema: classpath:/db/tables/hsql_database_tables.sql,classpath:/db/tables/security-schema.sql
    data: classpath:/db/users.sql,classpath:/db/clients.sql,classpath:/db/scopes.sql
logging:
  level:
    ROOT: INFO
    org.springframework.security: INFO

openid:
  connect:
    server:
      issuer: http://localhost:8080/
      topbarTitle: OpenID Connect Server
    crypto:
      keystore:
        path: classpath:keystore.jwks
      signing:
        defaultSignerKeyId: rsa1
        defaultSigningAlgorithmName: RS256
      encrypt:
        defaultAlgorithm: RSA1_5
        defaultDecryptionKeyId: rsa1
        defaultEncryptionKeyId: rsa1
    endpoints:
      api:
        whitelist.enabled: false
        approvedsite.enabled: false
        blacklist.enabled: false
        client.enabled: false
        data.enabled: false
        token.enabled: false
        scope.enabled: false
        stats.enabled: false   
      oidc:
        dynamicclientregistration.enabled: false
        jwksetpublishing.enabled: true
        userinfo.enabled: true
        discovery.enabled: true
      protectedresourceregistration.enabled: true
      
